/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs.isu.edu;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    App classUnderTest = new App();
    @Test public void testAppHasAGreeting() {
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test
    public void testSame(){
        assertEquals("Hello World",classUnderTest.getGreeting());
    }
}
